#!/usr/bin/env python3
"""Generate a 16.16 fixed-point sine table.

The kernel has no floating point and no libm, and computing this on the device
would mean either a polynomial approximation or a table built at boot. A table
generated at build time costs 1 KB of flash-mapped .rodata (UM-NATOS-011) and
nothing at runtime.

256 entries is one full turn, so an angle is a byte and wrapping is free.
"""
import math, io, sys

N = 256
ONE = 1 << 16
rows = []
for i in range(N):
    v = int(round(math.sin(2.0 * math.pi * i / N) * ONE))
    rows.append(v)

out = io.StringIO()
out.write("/* Generated by tools/gen_sintab.py - do not edit. */\n")
out.write("#ifndef NATOS_GENERATED_SINTAB_H\n#define NATOS_GENERATED_SINTAB_H\n\n")
out.write("#include <stdint.h>\n\n")
out.write("#define SIN_N   %du\n" % N)
out.write("#define FP_ONE  65536\n\n")
out.write("static const int32_t SIN_TAB[%d] = {\n" % N)
for i in range(0, N, 8):
    out.write("    " + ", ".join("%7d" % v for v in rows[i:i+8]) + ",\n")
out.write("};\n\n#endif\n")

path = sys.argv[1]
io.open(path, "w", encoding="utf-8", newline="\n").write(out.getvalue())
print("  sintab: %s (%d entries)" % (path, N))
